name: Monitor Upstream Change

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Commit SHA
        id: upstream
        run: |
          SHA=$(curl -u "u:${{ secrets.GITHUB_TOKEN }}" -s "https://api.github.com/repos/padavanonly/immortalwrt-mt798x-6.6/branches/openwrt-24.10-6.6" | jq -r .commit.sha)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Compare with Last Known SHA
        id: cache_sha
        uses: actions/cache@v3
        with:
          path: last_sha.txt
          key: upstream-sha-${{ steps.upstream.outputs.sha }}

      - name: Trigger Build
        if: steps.cache_sha.outputs.cache-hit != 'true'
        run: |
          echo "${{ steps.upstream.outputs.sha }}" > last_sha.txt

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/Build_cmcc_xr30-emmc_annawrt-24.10-k6.6.yml/dispatches \
            -d '{"ref":"main"}'
            
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
